module.exports = {
	content: [
	  './src/**/*.{astro,html,js,jsx,ts,tsx,vue}', // Asegúrate de incluir todas las rutas relevantes
	  // También puedes incluir otros patrones de archivos si es necesario
	],
	safelist: [
	  'text-2xl',
	  'text-center',
	  'text-xl',
	  'w-full',
	  'flex',
	  'justify-center',
	  'items-center',
	  'relative',
	  'm-10',
	  'max-w-xs',
	  'flex-col',
	  'overflow-hidden',
	  'rounded-lg',
	  'border',
	  'border-black-100',
	  'bg-white',
	  'shadow-md',
	  'h-60',
	  'rounded-xl',
	  'mt-4',
	  'px-5',
	  'pb-5',
	  'rounded-md',
	  'bg-green-700',
	  'py-2.5',
	  'text-sm',
	  'font-medium',
	  'text-white',
	  'hover:bg-green-900',
	  'focus:outline-none',
	  'focus:ring-4',
	  'focus:ring-blue-300',
	  'mr-2',
	  'h-6',
	  'w-6',
	  'mb-4',
	  'hover:bg-green-800',
	  'me-2',
	  'mb-2',
	  'dark:bg-green-600',
	  'dark:hover:bg-green-700',
	  'dark:focus:ring-green-800',
	  'cursor-pointer',
	  'font-bold',
	  'underline',
	  'flex',
	  'flex-col',
	  'p-10',
	  'gap-5',
	  'bg-gray-800',
	  'rounded-lg',
	  'relative',
	  'pb-16',
	  'text-green-700',
	  'absolute',
	  'bottom-5',
	  'right-10',
	  'font-bold',
	  'underline',
	  'rounded-full'
	],
	theme: {
	  extend: {},
	},
	plugins: [],
  };
  