export const temasSalud2 = [
  "Cómo mantener un peso saludable",
  "La importancia de la actividad física regular",
  "Cómo evitar el sedentarismo en el trabajo",
  "Los beneficios del ejercicio de resistencia",
  "Cómo mejorar la salud mental en adolescentes",
  "La relación entre la dieta y la salud del corazón",
  "Cómo prevenir la diabetes con una buena alimentación",
  "Los beneficios del ejercicio para la salud cerebral",
  "Cómo manejar el estrés académico",
  "La importancia de la salud mental en el trabajo",
  "Cómo mantener una vida activa en la vejez",
  "Los beneficios de una dieta mediterránea",
  "Cómo prevenir la hipertensión con una buena alimentación",
  "La relación entre la salud mental y el ejercicio",
  "Cómo mejorar tu salud inmunológica",
  "Los beneficios del ejercicio para la salud mental",
  "Cómo evitar el estrés en el hogar",
  "La importancia de la salud mental para el bienestar general",
  "Cómo prevenir la obesidad con una buena alimentación",
  "Los beneficios del ejercicio para la salud cardiovascular",
  "Cómo manejar el estrés en situaciones difíciles",
  "La relación entre la salud mental y la alimentación",
  "Cómo mejorar tu salud física y mental",
  "Los beneficios del ejercicio para la salud ósea",
  "Cómo evitar el estrés en el trabajo",
  "La importancia de la salud mental para la productividad",
  "Cómo mantener una dieta equilibrada en la vida diaria",
  "Los beneficios del ejercicio para la salud digestiva",
  "Cómo evitar el estrés en la vida cotidiana",
  "La relación entre la salud mental y la calidad del sueño",
  "Cómo mantener una buena salud mental en tiempos de crisis"
]