export const temasViajes2 = [
  "Cómo planificar un viaje alrededor del mundo",
  "Los mejores destinos para los amantes del vino",
  "Consejos para viajar durante la temporada alta",
  "Cómo evitar el estrés en los aeropuertos",
  "Los destinos más económicos para 2024",
  "Las mejores ciudades para disfrutar de la vida nocturna",
  "Consejos para viajar en avión con comodidad",
  "Los destinos más fascinantes para los amantes de la historia",
  "Cómo encontrar las mejores experiencias locales",
  "Las islas más hermosas que debes visitar",
  "Consejos para un viaje en bicicleta seguro y divertido",
  "Los mejores destinos de ecoturismo",
  "Cómo planificar un viaje de voluntariado",
  "Las ciudades más innovadoras para visitar",
  "Consejos para mantener tu presupuesto de viaje",
  "Los mejores destinos para una escapada de bienestar",
  "Cómo encontrar actividades gratuitas en cualquier destino",
  "Las rutas de carretera más épicas del mundo",
  "Consejos para viajar en pareja",
  "Los destinos más sorprendentes para 2024",
  "Cómo encontrar vuelos de última hora a buen precio",
  "Los mejores destinos para disfrutar de la naturaleza",
  "Consejos para viajar a destinos exóticos",
  "Las ciudades con la mejor arquitectura",
  "Cómo planificar un viaje gastronómico",
  "Los destinos más accesibles para personas con discapacidad",
  "Consejos para viajar en crucero",
  "Los mejores destinos para los amantes del cine",
  "Cómo planificar un viaje culturalmente inmersivo",
  "Las mejores rutas de viaje en autocaravana",
  "Consejos para evitar los imprevistos en tus viajes"
]