name: Push Automático

on:
  schedule:
    - cron: '00 03 * * *'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Git
      run: |
        git config --global user.name 'mateogalache'
        git config --global user.email 'mateogalache12@gmail.com'

    - name: Hacer cambios en el repositorio
      run: |
        # Añadir una línea con la fecha y hora actuales al archivo log.txt
        echo "Actualización automática: $(date)" >> log.txt
        git add log.txt

    - name: Commit and Push changes
      run: |
        git commit -m "Actualización automática diaria: $(date)"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
